### ISSUE TITLE
[Bug Report] Can Not remove "Update Available"

### ISSUE THREAD

**Issue by bkmo** [WAClient/WALC#195]
On version 0.2.2 The "update available" never disappears. If I click it the window closes and when re-opened from the tray icon the message remains.

**Comment by kawak1320** [comment]
same here!

**Comment by diederikvanbochove** [comment]
Same here too

**Comment by BenHerbst** [comment]
Same issue here too

**Comment by bkmo** [comment]
still same here

**Comment by dagmoller** [comment]
same problem here!!!

**Comment by Sadi58** [comment]
When clicked to update WhatsApp Web as usual an unusual dialog box appears:
![2022-08-25-13-35-10_Screenshot](https://user-images.githubusercontent.com/6375934/186643647-8a5aaf01-c338-479d-88f4-1bc7df39c2e6.jpg)
Clicking either button leads to a dead end where you have to quit and restart:
![2022-08-25-13-37-41_Screenshot](https://user-images.githubusercontent.com/6375934/186643939-dc509431-0f69-4a51-bc05-77f129498d93.jpg)
_KDE neon 5.25
KDE Plasma 5.25.4
KDE Frameworks 5.97.0
Qt 5.15.5_

**Comment by SteveGoodenough** [comment]
Same here. Didn't get this with the snap version (2.1), although there didn't seem to be a way to clear it too.

**Comment by bkmo** [comment]
we are preaching to the choir, this project is dead.

**Comment by Sadi58** [comment]
I've switched to WhatsDesk:
https://gitlab.com/zerkc/whatsdesk

**Comment by SteveGoodenough** [comment]
> I've switched to WhatsDesk: https://gitlab.com/zerkc/whatsdesk

thanks for the suggestion, I was using Whatsie in the meantime but that has some cert error

**Comment by Zzombiee2361** [comment]
Please check if this is still happening in the new beta version https://github.com/WAClient/WALC/releases/tag/v0.3.0-beta.0

**Comment by bkmo** [comment]
Update Available still persists after updating.

**Comment by Sadi58** [comment]
Does this still appear during (apparently unsuccessful) "updating" process?
In that case, it seems this (which I guess might be the underlying problem) hasn't been resolved yet.
![2022-12-21 10-38-16_000000017](https://user-images.githubusercontent.com/6375934/208849448-87c65cf6-a055-4c6b-adb4-066aab31a32d.jpg)

**Comment by Zzombiee2361** [comment]
@Sadi58 that issue is tracked here #172, which should be fixed.

Now this bug is a real head scratcher. If anyone had an idea how to fix it, I'm all ears.

**Comment by bkmo** [comment]
> Does this still appear during (apparently unsuccessful) "updating" process? In that case, it seems this (which I guess might be the underlying problem) hasn't been resolved yet. ![2022-12-21 10-38-16_000000017](https://user-images.githubusercontent.com/6375934/208849448-87c65cf6-a055-4c6b-adb4-066aab31a32d.jpg)

Yes this appears before the unsuccessful update.

**Comment by Zzombiee2361** [comment]
Whatsapp shows that no matter what user agent I use. I managed to get past that reliably but unfortunately that's the best I could do

**Comment by Sadi58** [comment]
I've tried the latest Beta, which made no difference. So I returned to "WALC-0.2.4.AppImage", and today I don't see this message during the usual updating process.
Probably it was due to an upstream bug, which has been fixed now.

**Comment by dagmoller** [comment]
I've not tested it, but i think you need to pass userAgent to Client object of whatsapp-web-electron.js
`this.whatsapp = new Client(pieBrowser, this, {userAgent: ....});`

**Comment by Zzombiee2361** [comment]
But of course! Why didn't I think of that?

From my testing the "Update Available" button would still appears, but if you click it, the app will reload and won't appear again. But at least it won't show the upgrade browser notice at all

**Comment by wokawoka** [comment]
same problem here

**Comment by Sadi58** [comment]
Yes, after a while it reappeared in the new beta version as well. ☹ Not a big deal though...
